apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  HTTP_PORT: {{ .Values.app.appconfig.httpport | quote }}
  HTTPS_PORT: {{ .Values.app.appconfig.httpsport | quote }}
  SUPPLIER_PURCHASE_URL: {{ .Values.app.appconfig.SUPPLIER_PURCHASE_URL }}
