apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DB_HOST: {{  .Values.app.dbconfig.host | b64enc}}
  DB_USER: {{  .Values.app.dbconfig.user | b64enc}}
  DB_PASSWORD: {{  .Values.app.dbconfig.password | b64enc}}
  DB_SCHEMA: {{  .Values.app.dbconfig.schema | b64enc}}
  SUPPLIER_USER: {{ .Values.app.appconfig.SUPPLIER_USER | b64enc}}
  SUPPLIER_PASSWORD: {{ .Values.app.appconfig.SUPPLIER_PASSWORD | b64enc}}

