app: 
  image:
    repository: 
    tag: 
  appconfig:
    httpport: 9080
    httpsport: 9443
    SUPPLIER_PURCHASE_URL: http://supplierdomain-service/supplierdomain/supplier/purchase/
    SUPPLIER_USER: admin
    SUPPLIER_PASSWORD: adminpwd
  dbconfig:
    host: 
    port: "5432"
    user: 
    password: 
    schema: 
    name: 
  scale:
    minReplica: 1
    maxReplicas: 3
  azureconfig:
    resourcegroup: 
    loadbalancerip: 
